language: cpp
dist: bionic
compiler:
  - gcc

install:
  - sudo apt update
  - sudo apt install -y g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - if [ $TRAVIS_OS_NAME = "linux" ]; then
      sudo bash .travis/install_intel_opencl.sh;
    fi;
  - sudo bash .travis/install_cuda.sh

script:
  - mkdir build_cuda
  - cd build_cuda
  - cmake -DGPU_CUDA_SUPPORT=ON -DCMAKE_BUILD_TYPE=RELWITHDEBINFO ..
  - make -j4
  - ./aplusb_cuda
  - cd ..
  - mkdir build_nocuda
  - cd build_nocuda
  - cmake -DGPU_CUDA_SUPPORT=OFF -DCMAKE_BUILD_TYPE=RELWITHDEBINFO ..
  - make -j4
  - ./aplusb_cuda
