name: Automatic Approve
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  automatic-approve:
    name: Automatic Approve
    runs-on: ubuntu-latest
    steps:
      - name: Automatic Approve
        uses: mheap/automatic-approve-action@v1
        with:
          token: ${{ secrets.PAT }} # The GitHub Token to use. Must be a personal access token with the repo scope. Project repo->Settings->Secrets->New secret: PAT=...
          workflows: "cmake.yml"
