name: Automatic Approve
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2
      with:
        github-token: "${{ secrets.PAT }}" # The GitHub Token to use. Must be a personal access token with the repo scope. Project repo->Settings->Secrets->New secret: PAT=...
